### ISSUE TITLE
Interested to help

### ISSUE THREAD

**Issue by qingwei91** [GiGurra/scalego#4]
Hi @GiGurra 

I am qingwei who replied you in mailing list, I am interested to help, shall we can first discussed about project goals, what communication tools do you prefer?

May I know which timezone are you in? I am in UTC +8 now

**Comment by GiGurra** [comment]
@buaya91 
Hi, cool,

Unfortunately I'm UTC +2/in Sweden

I'm usually on skype (search for GiGurra). If you dont like skype I guess we can set up a slack team ?

What do you prefer?

**Comment by qingwei91** [comment]
@GiGurra I prefer Slack

**Comment by GiGurra** [comment]
@buaya91 
I created a slack team now (scalego.slack.com) and sent an invite to the email address listed on your github account.
